version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
        - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true